export const circleConstants = {
  GENERATE_CIRCLES_REQUEST: 'GENERATE_CIRCLES_REQUEST',
  GENERATE_CIRCLES_SUCCESS: 'GENERATE_CIRCLES_SUCCESS',
  GENERATE_CIRCLES_FAILURE: 'GENERATE_CIRCLES_FAILURE',

  UPDATE_CIRCLE_REQUEST: 'UPDATE_CIRCLE_REQUEST',
  UPDATE_CIRCLE_SUCCESS: 'UPDATE_CIRCLE_SUCCESS',
  UPDATE_CIRCLE_FAILURE: 'UPDATE_CIRCLE_FAILURE',

  CREATE_CIRCLE_REQUEST: 'CREATE_CIRCLE_REQUEST',
  CREATE_CIRCLE_SUCCESS: 'CREATE_CIRCLE_SUCCESS',
  CREATE_CIRCLE_FAILURE: 'CREATE_CIRCLE_FAILURE',

  START_AJO_REQUEST: 'START_AJO_REQUEST',
  START_AJO_SUCCESS: 'START_AJO_SUCCESS',
  START_AJO_FAILURE: 'START_AJO_FAILURE',

  ACTIVE_CIRCLE: 'ACTIVE_CIRCLE',

  CLEAR_CIRCLE: 'CLEAR_CIRCLE',
};
