export const walletConstants = {
  UPDATE_WALLET_REQUEST: 'UPDATE_WALLET_REQUEST',
  UPDATE_WALLET_SUCCESS: 'UPDATE_WALLET_SUCCESS',
  UPDATE_WALLET_FAILURE: 'UPDATE_WALLET_FAILURE',

  GET_WALLET_REQUEST: 'GET_WALLET_REQUEST',
  GET_WALLET_SUCCESS: 'GET_WALLET_SUCCESS',
  GET_WALLET_FAILURE: 'GET_WALLET_FAILURE',

  DELETE_WALLET: 'DELETE_WALLET'
};


