require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'


platform :ios, '11.0'

target 'ajo' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'

  # pod 'RNFBMessaging', :path => '../node_modules/@react-native-firebase/messaging'

  pod 'RNFS', :path => '../node_modules/react-native-fs'
  pod 'react-native-paystack', :path => '../node_modules/react-native-paystack'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'



  target 'ajoTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end
